name: Node CI

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Run script
        run: bun run index.ts
      - run: |
          git config user.name github-actions || true
          git config user.email github-actions@github.com || true
          git add .
          git diff --exit-code || git commit -m "Update Playlist (GitHub Actions)"
          git diff --exit-code || git push -f origin main
