name: Node CI

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Run script
        run: bun run index.ts
      # - name: Archive production artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: live-matches-playlist
      #     path: live_matches_playlist.m3u
      # - uses: actions/checkout@v4
      # - uses: actions/download-artifact@v3
      #   with:
      #     name: live-matches-playlist
      #     path: live-matches-playlist.m3u
      - name: Display structure of files
        run: ls -R
