name: Update Playlist

on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches:
      - main

jobs:
  update_playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Update playlist
        run: bun index.ts

      - name: Push a commit
        run: |
          git config user.name update-playlist-bot
          git config user.email update-playlist-bot@users.noreply.github.com
          git add .
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Update Playlist (GitHub Actions)"
            git push origin main
          fi
